project:
  type: default
  render:
    - "cv-en-long.qmd"
    - "cv-en-short.qmd"
    - "cv-fr-long.qmd"
    - "cv-fr-short.qmd"

title: Example CV
author:
  name: Jane Doe
  email: jane.doe@example.org
  url: https://example.org
github: https://github.com/example
